rcache:
  host: 127.0.0.1
  port: 6379
  db: 0

gmail:
  user: errors@caresharing.eu
  password: password

pivotal:
  token: "token"
  project_id: 119519
  requested_by: "author name"
  owned_by: "author name"
