rcache:
  host: 127.0.0.1
  port: 6379
  db: 0

paypal:
  paypal_email: sa
  paypal_secret: foobar
  paypal_cert_id: 123
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

production:
  paypal_email: foo@example.com
  paypal_secret: supe
  paypal_cert_id: KLsdflsdfjHZSK326HEDS
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
