source 'http://rubygems.org'

gem 'rails', '3.0.12'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql'
gem 'paperclip', "2.7.0"
gem 'rake', "0.9.2.2"
gem 'cocaine'
gem "will_paginate"
gem "use_tinymce", :git => "https://github.com/mikehoward/use_tinymce.git"
gem "will_paginate-bootstrap", :git => "git://github.com/michaxze/will_paginate-bootstrap.git"

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
