#source "http://rubygems.org"
source :rubygems
source 'http://gems.github.com/'
gem 'echoe'

gem "eventmachine", :git => "http://github.com/markjeee/eventmachine.git", :branch => "v0.12.10-fixes"
gem "curb", :git => "http://github.com/markjeee/curb.git"
gem "rack", "= 1.1.0"
gem "thin"
gem "tiny_mce"
gem "geokit", :git => "http://github.com/andre/geokit-gem.git"

gem "rails", "= 2.3.10"

gem "ruby-openid-apps-discovery", "~> 1.2.0"
gem "omniauth", :git => "https://github.com/intridea/omniauth.git"
gem "mysql"
gem "mysql2", "< 0.3"
gem "haml"
gem "redis", "~> 2.0.10"
gem "yajl-ruby"
gem "libxml-ruby", ">= 1.1.4"
gem "jammit"
gem "tropo-webapi-ruby"
gem "addressable", :require => 'addressable/uri'
gem 'resque'
gem 'resque-restriction'
gem 'resque-scheduler', :require => 'resque_scheduler'
gem "json"
gem "carmen"
gem "activemerchant", ">=1.4.1"

#tunnrl
gem "net-ssh"
gem "highline"

gem "rmagick"
gem "paperclip"
gem "will_paginate"
gem "rest-client", :git => "https://github.com/archiloque/rest-client.git"

# Add Palmade Gems
gem "puppet_master", :git => "http://github.com/palmade/puppet_master.git", :branch => "development"
gem "db_essentials", :git => "http://github.com/palmade/db_essentials.git", :branch => "development"
gem "couch_potato", :git => "http://github.com/palmade/couch_potato.git", :branch => "development"
gem "http_service", :git => "http://github.com/palmade/http_service.git", :branch => "development"
gem "candy_wrapper", :git => "http://github.com/palmade/candy_wrapper.git", :branch => "development"

group :development, :test do
  gem "test-unit", "= 1.2.3"

#  gem "rspec"
#  gem "rspec-rails"

#  gem "cucumber"
#  gem "cucumber-rails"
#  gem "webrat"
end
