compress_assets:        on
package_assets:         on
embed_assets:           on
template_function:      _.template
package_path:           packages
javascript_compressor:  yui

javascripts:
  workspace:
    - public/javascripts/modernizr.custom.js
    - public/javascripts/jquery-1.6.2.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.preloader.js
    - public/javascripts/home.js
    - public/javascripts/common.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/jquery.autocomplete.pack.js
    - public/javascripts/jquery.validate.js
    - public/javascripts/ui/jquery.ui.core.js
    - public/javascripts/ui/jquery.ui.widget.js
    - public/javascripts/ui/jquery.ui.mouse.js
    - public/javascripts/ui/jquery.ui.slider.js
    - public/javascripts/ui/jquery.ui.tabs.js

stylesheets:
  common:
    - public/stylesheets/style.css
    - public/stylesheets/themes/base/jquery.ui.all.css
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.css
    - public/stylesheets/anythingslider.css
